/*
 * This file was automatically generated by EvoSuite
 * Fri May 24 09:32:19 GMT 2024
 */

package View;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import Model.Artigo;
import Model.Encomenda;
import Model.Transportadoras;
import View.Apresentacao;
import java.time.LocalDate;
import java.util.List;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Apresentacao_ESTest extends Apresentacao_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Apresentacao apresentacao0 = new Apresentacao();
      apresentacao0.printMenuEstatisticas();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Apresentacao apresentacao0 = new Apresentacao();
      apresentacao0.printMenuConsultas();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Apresentacao apresentacao0 = new Apresentacao();
      // Undeclared exception!
      try { 
        apresentacao0.printTop10((Map<String, Double>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("View.Output", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Apresentacao apresentacao0 = new Apresentacao();
      // Undeclared exception!
      try { 
        apresentacao0.printCarrinho((List<Integer>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("View.Output", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Apresentacao apresentacao0 = new Apresentacao();
      apresentacao0.printMainMenuLogOut();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Apresentacao apresentacao0 = new Apresentacao();
      apresentacao0.welcome();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Apresentacao apresentacao0 = new Apresentacao();
      apresentacao0.formulasTransportadora();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Apresentacao apresentacao0 = new Apresentacao();
      // Undeclared exception!
      try { 
        apresentacao0.printTransportadoras((Map<String, Transportadoras>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("View.Output", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Apresentacao apresentacao0 = new Apresentacao();
      apresentacao0.printMenuArtigo();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Apresentacao apresentacao0 = new Apresentacao();
      apresentacao0.printMessage("");
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Apresentacao apresentacao0 = new Apresentacao();
      apresentacao0.printMenuInicial();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Apresentacao apresentacao0 = new Apresentacao();
      apresentacao0.printMenuLogin();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Apresentacao apresentacao0 = new Apresentacao();
      apresentacao0.printSair();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Apresentacao apresentacao0 = new Apresentacao();
      // Undeclared exception!
      try { 
        apresentacao0.printEncomendas((List<Encomenda>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("View.Output", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Apresentacao apresentacao0 = new Apresentacao();
      Encomenda encomenda0 = new Encomenda();
      LocalDate localDate0 = encomenda0.getDataCriacao();
      // Undeclared exception!
      try { 
        apresentacao0.printArtigos((List<Artigo>) null, localDate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("View.Output", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Apresentacao apresentacao0 = new Apresentacao();
      apresentacao0.printMenuEncomenda();
  }
}
